format = """\
  $username\
  $hostname\
  $time\
  $kubernetes\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $aws\
  $env_var\
  $line_break\
  $jobs\
  $battery\
  $character\
"""
add_newline = false

[character]
success_symbol = "[ξ\\(✿ '‿'\\)ξ](yellow)"
error_symbol = "[人◕ ‿‿ ◕人](red)"

[directory]
truncation_length = 3
style = "purple"

[git_branch]
style = "green"

[hostname]
ssh_only = false
style = "blue"

[time]
disabled = false
style = "red"
